import SwiftUI
struct SmartContextCards: View {
    let contacts: [EchoContact]; let onReach: (EchoContact) -> Void; let onCompose: (EchoContact) -> Void
    var body: some View { VStack(spacing: 12) { header; if cards.isEmpty { allHealthyCard } else { ForEach(0..<cards.count) { i in smartCard(cards[i]) } } } }
    private var header: some View { HStack(spacing: 8) { Image(systemName: "sparkles").font(.system(size: 14)).foregroundStyle(EchoTheme.accentColor); Text("AI 洞察").font(.system(size: 16, weight: .bold, design: .rounded)); Spacer(); Text("\(cards.count) 条建议").font(.system(size: 12, weight: .medium)).foregroundStyle(.secondary) }.padding(.horizontal, 4) }
    private func smartCard(_ card: SmartCard) -> some View {
        VStack(spacing: 10) {
            HStack(spacing: 12) { ZStack { Circle().fill(card.color.opacity(0.15)).frame(width: 44, height: 44); Image(systemName: card.icon).font(.system(size: 18)).foregroundStyle(card.color) }; VStack(alignment: .leading, spacing: 3) { Text(card.title).font(.system(size: 15, weight: .semibold, design: .rounded)); Text(card.subtitle).font(.system(size: 13)).foregroundStyle(.secondary).lineLimit(2) }; Spacer(); if card.urgency == .high { Text("紧急").font(.system(size: 10, weight: .bold)).foregroundStyle(.white).padding(.horizontal, 8).padding(.vertical, 4).background(card.color).clipShape(Capsule()) } }
            HStack(spacing: 10) { Button { EchoHaptics.light(); onCompose(card.contact) } label: { HStack(spacing: 4) { Image(systemName: "text.bubble.fill").font(.system(size: 11)); Text("AI 写消息").font(.system(size: 13, weight: .semibold, design: .rounded)) }.foregroundStyle(card.color).frame(maxWidth: .infinity).padding(.vertical, 10).background(card.color.opacity(0.1)).clipShape(RoundedRectangle(cornerRadius: 10)) }; Button { EchoHaptics.medium(); onReach(card.contact) } label: { HStack(spacing: 4) { Image(systemName: "hand.wave.fill").font(.system(size: 11)); Text("立即联系").font(.system(size: 13, weight: .semibold, design: .rounded)) }.foregroundStyle(.white).frame(maxWidth: .infinity).padding(.vertical, 10).background(card.color.gradient).clipShape(RoundedRectangle(cornerRadius: 10)) } }
        }.padding(16).background(.ultraThinMaterial).clipShape(RoundedRectangle(cornerRadius: 16)).overlay(RoundedRectangle(cornerRadius: 16).stroke(card.color.opacity(0.2), lineWidth: 1)).shadow(color: card.color.opacity(0.08), radius: 8, x: 0, y: 4)
    }
    private var allHealthyCard: some View { HStack(spacing: 12) { ZStack { Circle().fill(Color(hex: "00D9A3").opacity(0.15)).frame(width: 44, height: 44); Image(systemName: "checkmark.seal.fill").font(.system(size: 18)).foregroundStyle(Color(hex: "00D9A3")) }; VStack(alignment: .leading, spacing: 2) { Text("一切正常").font(.system(size: 15, weight: .semibold, design: .rounded)); Text("你的所有关系都在健康状态。继续保持！").font(.system(size: 13)).foregroundStyle(.secondary) }; Spacer() }.padding(16).background(.ultraThinMaterial).clipShape(RoundedRectangle(cornerRadius: 16)) }
    private var cards: [SmartCard] {
        var result: [SmartCard] = []
        for c in contacts { let h = AIEngine.healthScore(for: c); let gap = Int(Date().timeIntervalSince(c.lastReachedOut ?? Date()) / 86400); if gap > 30 && (h.level == .critical || h.level == .fading) { result.append(SmartCard(contact: c, icon: "exclamationmark.triangle.fill", title: "\(c.givenName) 已经 \(gap) 天没联系了", subtitle: "你们的关系正在淡化。现在发一条消息，还来得及。", color: .red, urgency: .high)) } else if gap > 14 && h.level == .atRisk { result.append(SmartCard(contact: c, icon: "clock.badge.exclamationmark", title: "\(c.givenName) 好久没消息了", subtitle: "\(gap) 天了 — 一条简单的问候就能重新点燃联系。", color: .orange, urgency: .medium)) }; if gap > 60 && h.level != .critical { result.append(SmartCard(contact: c, icon: "arrow.triangle.2.circlepath", title: "和 \(c.givenName) 重连吧", subtitle: "\(gap) 天了 — 重连永远不会太晚。Echo 帮你写消息。", color: Color(hex: "9B59B6"), urgency: .low)) } }
        let streak = StreakManager.shared.calculateStreak(from: contacts.flatMap { $0.interactions }.map { $0.date }); if streak > 0 && streak < 3 { let placeholder = EchoContact(systemIdentifier: "placeholder", givenName: "", familyName: ""); result.append(SmartCard(contact: contacts.first ?? placeholder, icon: "flame.fill", title: "Streak 快断了！", subtitle: "你已经连续 \(streak) 天联系了某人。今天别断！", color: .orange, urgency: .high)) }
        return Array(result.prefix(4))
    }
}
struct SmartCard: Identifiable { let id = UUID(); let contact: EchoContact; let icon: String; let title: String; let subtitle: String; let color: Color; let urgency: Urgency }
enum Urgency { case low, medium, high }