import SwiftUI

struct SurveyView: View {
    var onComplete: (SurveyResult) -> Void
    @State private var step = 0
    @State private var showResult = false
    @State private var importantCount = 20
    @State private var categories: Set<Int> = [0]
    @State private var lastReachChoice = 2
    @State private var barrierChoice = 1
    @State private var hasLostSomeone = true
    @State private var lostCount = 3
    @State private var idealFrequency = 1
    @State private var guiltChoice = 0
    @State private var wantChangeChoice = 0
    @State private var helpfulFeatures: Set<Int> = [0, 1]
    private let totalSteps = 10
    var body: some View {
        ZStack {
            EchoBackground()
            VStack(spacing: 0) {
                if !showResult { progressBar.padding(.top, 56).padding(.bottom, 8).transition(.opacity) }
                ScrollView {
                    Group {
                        if showResult { resultView.transition(.asymmetric(insertion: .scale(scale: 0.92).combined(with: .opacity), removal: .opacity)) } else {
                            switch step {
                            case 0: page01_intro
                            case 1: page02_count
                            case 2: page03_categories
                            case 3: page04_lastReach
                            case 4: page05_barriers
                            case 5: page06_loss
                            case 6: page07_ideal
                            case 7: page08_desire
                            case 8: page09_expect
                            case 9: page10_preview
                            default: EmptyView()
                            }
                        }
                    }.animation(.spring(duration: 0.45, bounce: 0.1), value: step).animation(.spring(duration: 0.5, bounce: 0.2), value: showResult).padding(.horizontal, 28).padding(.bottom, 100)
                }
                if !showResult { bottomButton.padding(.horizontal, 28).padding(.bottom, 40).background(LinearGradient(colors: [Color.clear, EchoTheme.bgPrimary.opacity(0.95)], startPoint: .top, endPoint: .bottom).frame(height: 80)) }
            }
        }
    }
    private var progressBar: some View { HStack(spacing: 4) { ForEach(0..<totalSteps, id: \.self) { i in Capsule().fill(i <= step ? EchoTheme.accent : Color.white.opacity(0.12)).frame(height: 4).animation(.spring(duration: 0.3), value: step) } }.padding(.horizontal, 28) }
    private var page01_intro: some View { VStack(spacing: EchoTheme.spacing32) { Spacer().frame(height: 40); VStack(spacing: EchoTheme.spacing16) { ZStack { Circle().fill(EchoTheme.accent.opacity(0.06)).frame(width: 100, height: 100); Image(systemName: "wave.3.right").font(.system(size: 44, weight: .light)).foregroundStyle(EchoTheme.accent).symbolEffect(.pulse, options: .repeating) }; Text("Before we begin…").font(.caption.weight(.semibold)).foregroundStyle(EchoTheme.textTertiary).textCase(.uppercase).tracking(2) }; VStack(spacing: EchoTheme.spacing12) { Text("Let's talk about\nthe people in your life.").font(.system(size: 28, weight: .bold, design: .rounded)).foregroundStyle(EchoTheme.textPrimary).multilineTextAlignment(.center); Text("This takes 2 minutes.\nYour answers shape how Echo works for you.").font(.subheadline).foregroundStyle(EchoTheme.textSecondary).multilineTextAlignment(.center) }; VStack(spacing: EchoTheme.spacing12) { infoPill(icon: "lock.fill", text: "100% private — answers stay on your device"); infoPill(icon: "hand.point.up.fill", text: "No right or wrong answers"); infoPill(icon: "heart.fill", text: "Just honest reflection") }.padding(.top, 8) } }
    private func infoPill(icon: String, text: String) -> some View { HStack(spacing: 8) { Image(systemName: icon).font(.system(size: 12)).foregroundStyle(EchoTheme.accent.opacity(0.7)); Text(text).font(.caption).foregroundStyle(EchoTheme.textTertiary) }.padding(.horizontal, 16).padding(.vertical, 8).background(EchoTheme.bgCard).clipShape(Capsule()) }
    private var page02_count: some View { surveyPage(eyebrow: "Step 1 of 9", icon: "person.3.sequence.fill", question: "How many people in your life\ntruly matter to you?") { VStack(spacing: EchoTheme.spacing16) { Text("\(importantCount)").font(.system(size: 72, weight: .bold, design: .rounded)).foregroundStyle(EchoTheme.accent).contentTransition(.numericText()).animation(.spring(duration: 0.3), value: importantCount); Stepper(value: $importantCount, in: 1...500, step: 1) { Text("People who matter").font(.subheadline).foregroundStyle(EchoTheme.textSecondary) }.labelsHidden().tint(EchoTheme.accent); Text("Family, close friends, mentors, colleagues, old classmates…\nAnyone you'd want to stay connected with.").font(.caption).foregroundStyle(EchoTheme.textTertiary).multilineTextAlignment(.center); quickButtons(options: [("5", 5), ("10", 10), ("20", 20), ("50", 50), ("100+", 100)], current: importantCount) { importantCount = $0 } } } }
    private var page03_categories: some View { surveyPage(eyebrow: "Step 2 of 9", icon: "square.grid.2x2.fill", question: "Who are these people\nto you?") { VStack(spacing: EchoTheme.spacing8) { Text("Select all that apply").font(.caption).foregroundStyle(EchoTheme.textTertiary).padding(.bottom, 4); ForEach(Array(categoryOptions.enumerated()), id: \.offset) { index, cat in Button { EchoHaptics.selection(); withAnimation(.spring(duration: 0.25)) { if categories.contains(index) { categories.remove(index) } else { categories.insert(index) } } } label: { HStack(spacing: 12) { Text(cat.emoji).font(.title3); Text(cat.label).font(.body.weight(.medium)).foregroundStyle(EchoTheme.textPrimary); Spacer(); Image(systemName: categories.contains(index) ? "checkmark.circle.fill" : "circle").font(.system(size: 22)).foregroundStyle(categories.contains(index) ? EchoTheme.accent : Color.white.opacity(0.2)) }.padding(.horizontal, 20).frame(height: 56).background(categories.contains(index) ? EchoTheme.accent.opacity(0.1) : EchoTheme.bgCard).clipShape(RoundedRectangle(cornerRadius: 14, style: .continuous)).overlay(RoundedRectangle(cornerRadius: 14, style: .continuous).stroke(categories.contains(index) ? EchoTheme.accent.opacity(0.3) : Color.white.opacity(0.06), lineWidth: 1)) }.buttonStyle(.plain) } } } }
    private var categoryOptions: [(emoji: String, label: String)] { [("👨‍👩‍👧‍👦", "Family & relatives"), ("🤝", "Close friends"), ("💼", "Colleagues & work"), ("🎓", "Mentors & teachers"), ("❤️", "Partner / significant other"), ("🌍", "Old friends I've drifted from")] }
    private var page04_lastReach: some View { surveyPage(eyebrow: "Step 3 of 9", icon: "clock.fill", question: "When was the last time you\nreached out to most of them?") { VStack(spacing: EchoTheme.spacing8) { ForEach(Array(reachOptions.enumerated()), id: \.offset) { index, option in selectableCard(emoji: option.emoji, text: option.text, subtitle: option.subtitle, isSelected: lastReachChoice == index) { EchoHaptics.selection(); withAnimation(.spring(duration: 0.25)) { lastReachChoice = index } } } } } }
    private var reachOptions: [(emoji: String, text: String, subtitle: String)] { [("😌", "This week", "I'm pretty good at staying in touch"), ("📅", "This month", "I try, but some slip through"), ("🗓️", "A few months ago", "Life gets busy, you know?"), ("🤔", "Honestly… I can't remember", "It's been a while for most of them")] }
    private var page05_barriers: some View { surveyPage(eyebrow: "Step 4 of 9", icon: "hand.raised.fill", question: "What usually stops you\nfrom reaching out?") { VStack(spacing: EchoTheme.spacing8) { ForEach(Array(barrierOptions.enumerated()), id: \.offset) { index, option in selectableCard(emoji: option.emoji, text: option.text, subtitle: option.subtitle, isSelected: barrierChoice == index) { EchoHaptics.selection(); withAnimation(.spring(duration: 0.25)) { barrierChoice = index } } } } } }
    private var barrierOptions: [(emoji: String, text: String, subtitle: String)] { [("⏰", "Too busy", "Work, life, everything piles up"), ("🤷", "I forget", "It just slips my mind"), ("😰", "Don't know what to say", "After a while it feels awkward"), ("📵", "Don't want to bother them", "They're probably busy too")] }
    private var page06_loss: some View { surveyPage(eyebrow: "Step 5 of 9", icon: "heart.slash", question: "Have you ever lost touch\nwith someone you cared about?") { VStack(spacing: EchoTheme.spacing16) { HStack(spacing: EchoTheme.spacing12) { Button { EchoHaptics.selection(); withAnimation { hasLostSomeone = true } } label: { VStack(spacing: 6) { Text("😔").font(.title); Text("Yes").font(.headline) }.frame(maxWidth: .infinity).frame(height: 80).background(hasLostSomeone ? EchoTheme.overdue.opacity(0.1) : EchoTheme.bgCard).clipShape(RoundedRectangle(cornerRadius: 14, style: .continuous)).overlay(RoundedRectangle(cornerRadius: 14, style: .continuous).stroke(hasLostSomeone ? EchoTheme.overdue.opacity(0.4) : Color.white.opacity(0.06), lineWidth: 1.5)) }.buttonStyle(.plain); Button { EchoHaptics.selection(); withAnimation { hasLostSomeone = false } } label: { VStack(spacing: 6) { Text("🙂").font(.title); Text("Not really").font(.headline) }.frame(maxWidth: .infinity).frame(height: 80).background(!hasLostSomeone ? EchoTheme.success.opacity(0.1) : EchoTheme.bgCard).clipShape(RoundedRectangle(cornerRadius: 14, style: .continuous)).overlay(RoundedRectangle(cornerRadius: 14, style: .continuous).stroke(!hasLostSomeone ? EchoTheme.success.opacity(0.4) : Color.white.opacity(0.06), lineWidth: 1.5)) }.buttonStyle(.plain) }; if hasLostSomeone { VStack(spacing: EchoTheme.spacing12) { Text("Roughly how many people\nhave drifted away like this?").font(.subheadline).foregroundStyle(EchoTheme.textSecondary).multilineTextAlignment(.center); Text("\(lostCount)").font(.system(size: 48, weight: .bold, design: .rounded)).foregroundStyle(EchoTheme.overdue).contentTransition(.numericText()); Stepper(value: $lostCount, in: 1...200, step: 1) { Text("People lost touch with") }.labelsHidden().tint(EchoTheme.overdue); quickButtons(options: [("1-2", 2), ("3-5", 5), ("10+", 10), ("20+", 20)], current: lostCount) { lostCount = $0 } }.transition(.opacity.combined(with: .scale(scale: 0.95))) }; VStack(spacing: 6) { Text("「时间不会让你失去谁，"); Text("遗忘才会。」") }.font(.system(.caption, design: .serif)).foregroundStyle(EchoTheme.textTertiary).italic().padding(.top, 8) } } }
    private var page07_ideal: some View { surveyPage(eyebrow: "Step 6 of 9", icon: "calendar.badge.clock", question: "How often would you\nideally check in with each person?") { VStack(spacing: EchoTheme.spacing8) { ForEach(Array(frequencyOptions.enumerated()), id: \.offset) { index, option in selectableCard(emoji: option.emoji, text: option.text, subtitle: option.subtitle, isSelected: idealFrequency == index) { EchoHaptics.selection(); withAnimation(.spring(duration: 0.25)) { idealFrequency = index } } } } } }
    private var frequencyOptions: [(emoji: String, text: String, subtitle: String)] { [("📞", "Every few days", "Close family, partner, best friends"), ("💬", "Once a week", "Good friends, active colleagues"), ("📧", "Once a month", "Extended network, occasional check-in"), ("✉️", "Every few months", "Old friends, mentors, distant contacts")] }
    private var page08_desire: some View { surveyPage(eyebrow: "Step 7 of 9", icon: "sparkles", question: "How does it feel when you\nrealize you've lost touch?") { VStack(spacing: EchoTheme.spacing8) { ForEach(Array(guiltOptions.enumerated()), id: \.offset) { index, option in selectableCard(emoji: option.emoji, text: option.text, subtitle: option.subtitle, isSelected: guiltChoice == index) { EchoHaptics.selection(); withAnimation(.spring(duration: 0.25)) { guiltChoice = index } } } }; VStack(spacing: EchoTheme.spacing12) { Text("If you could never lose touch again…").font(.subheadline.weight(.medium)).foregroundStyle(EchoTheme.textSecondary); ForEach(Array(desireOptions.enumerated()), id: \.offset) { index, option in Button { EchoHaptics.selection(); withAnimation(.spring(duration: 0.25)) { wantChangeChoice = index } } label: { HStack(spacing: 12) { Text(option.emoji).font(.title3); Text(option.text).font(.body.weight(.medium)).foregroundStyle(EchoTheme.textPrimary).multilineTextAlignment(.leading); Spacer(); if wantChangeChoice == index { Image(systemName: "checkmark.circle.fill").foregroundStyle(EchoTheme.accent) } }.padding(.horizontal, 20).frame(minHeight: 56).background(wantChangeChoice == index ? EchoTheme.accent.opacity(0.1) : EchoTheme.bgCard).clipShape(RoundedRectangle(cornerRadius: 14, style: .continuous)).overlay(RoundedRectangle(cornerRadius: 14, style: .continuous).stroke(wantChangeChoice == index ? EchoTheme.accent.opacity(0.3) : Color.white.opacity(0.06), lineWidth: 1)) }.buttonStyle(.plain) } }.padding(.top, 8) } }
    private var guiltOptions: [(emoji: String, text: String, subtitle: String)] { [("😔", "Guilty", "I know I should do better"), ("😢", "Sad", "I miss them and wish I hadn't"), ("😤", "Frustrated", "Life gets in the way"), ("🤷", "It happens", "People drift apart naturally")] }
    private var desireOptions: [(emoji: String, text: String)] { [("🔥", "I'd do whatever it takes"), ("👍", "I'd like that, if it's easy enough"), ("🤔", "I'm not sure I'd stick with it")] }
    private var page09_expect: some View { surveyPage(eyebrow: "Step 8 of 9", icon: "wand.and.stars", question: "What would actually help\nyou stay in touch?") { VStack(spacing: EchoTheme.spacing8) { Text("Select all that sound useful").font(.caption).foregroundStyle(EchoTheme.textTertiary); ForEach(Array(featureOptions.enumerated()), id: \.offset) { index, feature in Button { EchoHaptics.selection(); withAnimation(.spring(duration: 0.25)) { if helpfulFeatures.contains(index) { helpfulFeatures.remove(index) } else { helpfulFeatures.insert(index) } } } label: { HStack(spacing: 12) { ZStack { Circle().fill(helpfulFeatures.contains(index) ? EchoTheme.accent.opacity(0.15) : Color.white.opacity(0.04)).frame(width: 36, height: 36); Image(systemName: feature.icon).font(.system(size: 14, weight: .medium)).foregroundStyle(helpfulFeatures.contains(index) ? EchoTheme.accent : EchoTheme.textTertiary) }; VStack(alignment: .leading, spacing: 2) { Text(feature.title).font(.subheadline.weight(.medium)).foregroundStyle(EchoTheme.textPrimary); Text(feature.subtitle).font(.caption).foregroundStyle(EchoTheme.textTertiary) }; Spacer(); Image(systemName: helpfulFeatures.contains(index) ? "checkmark.circle.fill" : "circle").font(.system(size: 20)).foregroundStyle(helpfulFeatures.contains(index) ? EchoTheme.accent : Color.white.opacity(0.2)) }.padding(.horizontal, 16).frame(minHeight: 60).background(helpfulFeatures.contains(index) ? EchoTheme.accent.opacity(0.06) : EchoTheme.bgCard).clipShape(RoundedRectangle(cornerRadius: 14, style: .continuous)).overlay(RoundedRectangle(cornerRadius: 14, style: .continuous).stroke(helpfulFeatures.contains(index) ? EchoTheme.accent.opacity(0.2) : Color.white.opacity(0.06), lineWidth: 1)) }.buttonStyle(.plain) } } } }
    private var featureOptions: [(icon: String, title: String, subtitle: String)] { [("bell.badge.fill", "Smart reminders", "Know when it's time to reach out — before it's too late"), ("list.number", "Priority list", "See who you haven't talked to, sorted by urgency"), ("hand.wave.fill", "One-tap reach out", "Call, text, or email without leaving the app"), ("clock.arrow.2.circlepath", "Interaction history", "Every conversation logged automatically"), ("flame.fill", "Streaks & milestones", "Gamify staying connected"), ("chart.bar.fill", "Relationship insights", "See patterns in how you connect")] }
    private var page10_preview: some View { VStack(spacing: EchoTheme.spacing24) { Spacer().frame(height: 20); VStack(spacing: EchoTheme.spacing12) { ZStack { Circle().fill(EchoTheme.accent.opacity(0.06)).frame(width: 88, height: 88); Image(systemName: "wave.3.right.fill").font(.system(size: 38, weight: .light)).foregroundStyle(EchoTheme.accent).symbolEffect(.pulse, options: .repeating) }; Text("Here's what Echo\nwill do for you").font(.system(size: 26, weight: .bold, design: .rounded)).foregroundStyle(EchoTheme.textPrimary).multilineTextAlignment(.center) }; VStack(spacing: EchoTheme.spacing12) { previewRow(icon: "person.3.sequence.fill", text: "Track \(importantCount) people who matter to you"); previewRow(icon: "bell.badge.fill", text: "Remind you every \(frequencyOptions[idealFrequency].text.lowercased())"); previewRow(icon: "hand.wave.fill", text: "One tap to call, text, or email"); if helpfulFeatures.contains(2) { previewRow(icon: "clock.arrow.2.circlepath", text: "Log every interaction automatically") }; if helpfulFeatures.contains(4) { previewRow(icon: "flame.fill", text: "Build streaks for staying connected") }; previewRow(icon: "lock.fill", text: "Everything stays on your device") }.padding(EchoTheme.spacing16).background(EchoTheme.bgCard).clipShape(RoundedRectangle(cornerRadius: 16, style: .continuous)).overlay(RoundedRectangle(cornerRadius: 16, style: .continuous).stroke(EchoTheme.accent.opacity(0.12), lineWidth: 0.5)); Text("You're \(barrierOptions[barrierChoice].text.lowercased()). Echo fixes that.").font(.subheadline.weight(.medium)).foregroundStyle(EchoTheme.accent) } }
    private func previewRow(icon: String, text: String) -> some View { HStack(spacing: 12) { Image(systemName: icon).font(.system(size: 14, weight: .medium)).foregroundStyle(EchoTheme.accent).frame(width: 28, height: 28).background(EchoTheme.accent.opacity(0.1)).clipShape(Circle()); Text(text).font(.subheadline).foregroundStyle(EchoTheme.textPrimary); Spacer() } }
    private var resultView: some View { VStack(spacing: EchoTheme.spacing24) { Spacer().frame(height: 20); VStack(spacing: EchoTheme.spacing4) { Text("\(importantCount)").font(.system(size: 80, weight: .bold, design: .rounded)).foregroundStyle(EchoTheme.accent); Text("people matter to you").font(.headline).foregroundStyle(EchoTheme.textSecondary) }; VStack(spacing: EchoTheme.spacing8) { insightCard(icon: "clock", color: EchoTheme.overdue, title: "Your gap", value: reachOptions[lastReachChoice].text, detail: reachInsight); if hasLostSomeone { insightCard(icon: "heart.slash", color: EchoTheme.overdue, title: "People lost", value: "~\(lostCount)", detail: "Relationships that faded because you lost touch") }; insightCard(icon: "calendar", color: EchoTheme.accent, title: "Your ideal", value: frequencyOptions[idealFrequency].text, detail: "That's \(idealReachPerYear) check-ins per year across \(importantCount) people"); insightCard(icon: "hand.raised", color: Color.orange, title: "Your barrier", value: barrierOptions[barrierChoice].text, detail: "Echo's reminders solve exactly this") }; VStack(spacing: EchoTheme.spacing12) { Text(verdictText).font(.title3.weight(.semibold)).foregroundStyle(EchoTheme.textPrimary).multilineTextAlignment(.center); Text("Echo can fix this. It takes 10 seconds a day.\nLet's set it up — it takes 2 minutes.").font(.subheadline).foregroundStyle(EchoTheme.textSecondary).multilineTextAlignment(.center) }.padding(.top, 8); Button { EchoHaptics.medium(); onComplete(buildResult()) } label: { Text("Let's Fix This").font(.headline).frame(maxWidth: .infinity).frame(height: 54) }.buttonStyle(.borderedProminent).tint(EchoTheme.accent).padding(.top, 8) } }
    private func insightCard(icon: String, color: Color, title: String, value: String, detail: String) -> some View { HStack(spacing: EchoTheme.spacing12) { ZStack { Circle().fill(color.opacity(0.12)).frame(width: 40, height: 40); Image(systemName: icon).font(.system(size: 16, weight: .medium)).foregroundStyle(color) }; VStack(alignment: .leading, spacing: 2) { Text(title).font(.caption).foregroundStyle(EchoTheme.textTertiary); Text(value).font(.subheadline.weight(.semibold)).foregroundStyle(EchoTheme.textPrimary); Text(detail).font(.caption2).foregroundStyle(EchoTheme.textTertiary).lineLimit(2) }; Spacer() }.padding(EchoTheme.spacing12).background(EchoTheme.bgCard).clipShape(RoundedRectangle(cornerRadius: 12, style: .continuous)) }
    private var reachInsight: String { switch lastReachChoice { case 0: return "You're doing well — Echo keeps the streak"; case 1: return "About \(Int(Double(importantCount) * 0.5)) of your \(importantCount) are waiting"; case 2: return "Most haven't heard from you in months"; default: return "If you can't remember, they can't either" } }
    private var idealReachPerYear: String { let perPerson: Int; switch idealFrequency { case 0: perPerson = 120; case 1: perPerson = 52; case 2: perPerson = 12; default: perPerson = 4 }; let total = perPerson * importantCount; if total >= 1000 { return "\(total / 1000)k+" }; return "\(total)" }
    private var verdictText: String { if hasLostSomeone && lostCount >= 5 { return "You've lost touch with ~\(lostCount) people.\n\(importantCount) more could slip away too." } else if lastReachChoice >= 2 { return "Most of your \(importantCount) people\nhaven't heard from you in months." } else if barrierChoice == 1 { return "You don't forget on purpose.\nYou just need the right reminder." } else { return "You're doing okay —\nbut Echo makes it effortless." } }
    private func buildResult() -> SurveyResult { SurveyResult(importantCount: importantCount, categories: categories.map { categoryOptions[$0].label }, lastReachChoice: lastReachChoice, barrierChoice: barrierChoice, hasLostSomeone: hasLostSomeone, lostCount: lostCount, idealFrequency: idealFrequency, guiltChoice: guiltChoice, wantChange: wantChangeChoice, helpfulFeatures: helpfulFeatures.map { featureOptions[$0].title }) }
    private var bottomButton: some View { Button { EchoHaptics.light(); if step < totalSteps - 1 { withAnimation { step += 1 } } else { withAnimation { showResult = true } } } label: { HStack { Text(step < totalSteps - 1 ? "Continue" : "See My Results").font(.headline); if step < totalSteps - 1 { Image(systemName: "arrow.right").font(.system(size: 14, weight: .semibold)) } }.frame(maxWidth: .infinity).frame(height: 54) }.buttonStyle(.borderedProminent).tint(EchoTheme.accent) }
    private func surveyPage<S: View>(eyebrow: String, icon: String, question: String, @ViewBuilder content: () -> S) -> some View { VStack(spacing: EchoTheme.spacing24) { Spacer().frame(height: 16); VStack(spacing: EchoTheme.spacing12) { ZStack { Circle().fill(EchoTheme.accent.opacity(0.06)).frame(width: 64, height: 64); Image(systemName: icon).font(.system(size: 28, weight: .light)).foregroundStyle(EchoTheme.accent) }; Text(eyebrow).font(.caption.weight(.medium)).foregroundStyle(EchoTheme.textTertiary).textCase(.uppercase).tracking(1.5) }; Text(question).font(.system(size: 24, weight: .bold, design: .rounded)).foregroundStyle(EchoTheme.textPrimary).multilineTextAlignment(.center); content() } }
    private func selectableCard(emoji: String, text: String, subtitle: String, isSelected: Bool, action: @escaping () -> Void) -> some View { Button(action: action) { HStack(spacing: 12) { Text(emoji).font(.title3); VStack(alignment: .leading, spacing: 2) { Text(text).font(.body.weight(.medium)).foregroundStyle(EchoTheme.textPrimary); Text(subtitle).font(.caption).foregroundStyle(EchoTheme.textTertiary) }; Spacer(); Image(systemName: isSelected ? "checkmark.circle.fill" : "circle").font(.system(size: 22)).foregroundStyle(isSelected ? EchoTheme.accent : Color.white.opacity(0.2)) }.padding(.horizontal, 20).frame(height: 64).background(isSelected ? EchoTheme.accent.opacity(0.08) : EchoTheme.bgCard).clipShape(RoundedRectangle(cornerRadius: 14, style: .continuous)).overlay(RoundedRectangle(cornerRadius: 14, style: .continuous).stroke(isSelected ? EchoTheme.accent.opacity(0.3) : Color.white.opacity(0.06), lineWidth: 1)) }.buttonStyle(.plain) }
    private func quickButtons(options: [(String, Int)], current: Int, action: @escaping (Int) -> Void) -> some View { HStack(spacing: 8) { ForEach(Array(options.enumerated()), id: \.offset) { _, option in Button { EchoHaptics.selection(); withAnimation(.spring(duration: 0.2)) { action(option.1) } } label: { Text(option.0).font(.caption.weight(.semibold)).foregroundStyle(current == option.1 ? .white : EchoTheme.textSecondary).padding(.horizontal, 16).frame(height: 36).background(current == option.1 ? EchoTheme.accent : EchoTheme.bgCard).clipShape(Capsule()).overlay(Capsule().stroke(current == option.1 ? Color.clear : Color.white.opacity(0.1), lineWidth: 1)) }.buttonStyle(.plain) } } }
}

struct SurveyResult: Codable { let importantCount: Int; let categories: [String]; let lastReachChoice: Int; let barrierChoice: Int; let hasLostSomeone: Bool; let lostCount: Int; let idealFrequency: Int; let guiltChoice: Int; let wantChange: Int; let helpfulFeatures: [String] }
