import SwiftUI
import StoreKit
extension EchoTheme {
    static var accentColor: Color { accent }
    static var cardGradient: LinearGradient { LinearGradient(colors: [bgCard, bgSecondary], startPoint: .topLeading, endPoint: .bottomTrailing) }
    static var cardRadius: CGFloat { radius16 }
    static var backgroundGradient: LinearGradient { LinearGradient(colors: [bgPrimary, Color(red: 0.02, green: 0.025, blue: 0.04)], startPoint: .top, endPoint: .bottom) }
    static var darkBackground: Color { bgPrimary }
    static var cardBackground: Color { bgCard }
    static var gradient: LinearGradient { LinearGradient(colors: [accent, Color(hex: "00F5FF")], startPoint: .leading, endPoint: .trailing) }
    static var sectionFont: Font { .system(size: 16, weight: .bold) }
    static var captionFont: Font { .system(size: 12) }
    static var titleFont: Font { .system(size: 22, weight: .bold, design: .rounded) }
    static var bodyFont: Font { .system(size: 15) }
}
extension Color { init(hex: String) { let h = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted); var v: UInt64 = 0; Scanner(string: h).scanHexInt64(&v); let r, g, b: UInt64; (r, g, b) = (v >> 16, v >> 8 & 0xFF, v & 0xFF); self.init(.sRGB, red: Double(r) / 255, green: Double(g) / 255, blue: Double(b) / 255) } }
extension StreakManager { static let shared = StreakManager(); func calculateStreak(from dates: [Date]) -> Int { let cal = Calendar.current; let sorted = Set(dates.map { cal.startOfDay(for: $0) }).sorted(by: >); guard !sorted.isEmpty else { return 0 }; var streak = 0; var check = cal.startOfDay(for: Date()); if sorted.first == check { while sorted.contains(check) { streak += 1; check = cal.date(byAdding: .day, value: -1, to: check)! } } else if let y = cal.date(byAdding: .day, value: -1, to: check), sorted.first == y { check = y; while sorted.contains(check) { streak += 1; check = cal.date(byAdding: .day, value: -1, to: check)! } }; return streak } }
extension EchoHaptics { static func tap() { UIImpactFeedbackGenerator(style: .light).impactOccurred(intensity: 0.6) }; static func confirm() { UIImpactFeedbackGenerator(style: .medium).impactOccurred(intensity: 0.8) }; static func impact() { UIImpactFeedbackGenerator(style: .heavy).impactOccurred() }; static func warning() { UINotificationFeedbackGenerator().notificationOccurred(.warning) }; static func celebrate() { let g = UIImpactFeedbackGenerator(style: .heavy); g.impactOccurred(); DispatchQueue.main.asyncAfter(deadline: .now() + 0.15) { g.impactOccurred(intensity: 0.6) }; DispatchQueue.main.asyncAfter(deadline: .now() + 0.3) { g.impactOccurred(intensity: 0.3) } }; static func wave() { let g = UIImpactFeedbackGenerator(style: .soft); for i in 0..<3 { DispatchQueue.main.asyncAfter(deadline: .now() + Double(i) * 0.08) { g.impactOccurred(intensity: 0.3 + Double(i) * 0.2) } } } }
extension AIEngine { static func smartSearch(query: String, in contacts: [EchoContact]) -> [(EchoContact, Double)] { let q = query.lowercased(); return contacts.filter { c in c.fullName.lowercased().contains(q) || c.givenName.lowercased().contains(q) || (c.companyName?.lowercased().contains(q) ?? false) || c.notes.contains { $0.content.lowercased().contains(q) } || c.interactions.contains { $0.note.lowercased().contains(q) } }.map { ($0, 1.0) } } }
class TrialManager: ObservableObject { static let shared = TrialManager(); @AppStorage("trial_start_date") private var trialStartDate: Double = 0; @AppStorage("has_used_trial") private var hasUsedTrial: Bool = false; var isInTrial: Bool { guard hasUsedTrial else { return false }; let elapsed = Date().timeIntervalSince1970 - trialStartDate; return elapsed < 3 * 24 * 60 * 60 }; var daysRemaining: Int { guard hasUsedTrial else { return 3 }; let remaining = 3 * 24 * 60 * 60 - (Date().timeIntervalSince1970 - trialStartDate); return max(0, Int(remaining / 86400)) }; func startTrial() { trialStartDate = Date().timeIntervalSince1970; hasUsedTrial = true } }
enum OnboardingStep: String, CaseIterable { case survey, registration, valueProp, paywall, importContacts, done }
struct OnboardingState { @AppStorage("onboarding_step") static var currentStepRaw: String = OnboardingStep.survey.rawValue; @AppStorage("onboarding_complete") static var isComplete: Bool = false; static var currentStep: OnboardingStep { OnboardingStep(rawValue: currentStepRaw) ?? .survey }; static func complete(_ step: OnboardingStep) { let all = OnboardingStep.allCases; if let idx = all.firstIndex(of: step), idx + 1 < all.count { currentStepRaw = all[idx + 1].rawValue }; if step == .done { isComplete = true } }; static func reset() { currentStepRaw = OnboardingStep.survey.rawValue; isComplete = false } }
struct SurveyResult { var relationshipCount: Int; var biggestChallenge: String; var preferredFrequency: String; var motivator: String }